apiVersion: v1
kind: Config

clusters:
- name: zauqilab-cluster
  cluster:
    server: https://api.k3s.zauqilab.com:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpnME1Ua3hNakl3SGhjTk1qWXdOVEV3TVRJeE9EUXlXaGNOTXpZd05UQTNNVEl4T0RReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpnME1Ua3hNakl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUSzR3djZtYW9wbHFRVGliT2NMcExRKzhYM0laaGtNdHNqMy9yNHBtUWwKQWhTSGlBQzVmUWNNUnUzV0lkeDRUNGVlRkNJdTQzV2YzUkl6NmFNcVFtR1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVNiU1d2ZTJTakVFT3VjTFlFMmdvCmJ5WUlYQU13Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWHR4eG01Ym9TemlCSEI1SFN3NktrU1p0MWNsbHR4QjMKRFpUWGloREo0Mm9DSUhuNURLZlpZZUQzR00wRmZydmtWMk9yeXIyNTNqaGdzbnVPbHBIRk45ODQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

contexts:
- name: student-01@student-01
  context:
    cluster: zauqilab-cluster
    namespace: student-01
    user: student-01

current-context: student-01@student-01

users:
- name: student-01
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImV1TF9vSWtvOTBLak1TNFZwVEEweVlwalBVcmMzT01kNGFzXzFYTlBoaFEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzkwODYyODMxLCJpYXQiOjE3ODgyNzA4MzEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZmU3ZTNiNjEtYzYwMy00MTk2LWIxYmEtZWY0ZWI1MDZkYWQxIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJzdHVkZW50LTAxIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InN0dWRlbnQtMDEiLCJ1aWQiOiI5YjM1ZGU1Ny1jNGQ3LTRmMDItOWI4YS1hZTU5ODRhMzY1NTIifX0sIm5iZiI6MTc4ODI3MDgzMSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN0dWRlbnQtMDE6c3R1ZGVudC0wMSJ9.D1GS6OVoCHwsJDm_0lxgCa8N1uM1s9VOsA7kMdddwiAEjYjbqH2wWUl0FymIj6HMlv85EiQ41t2Af-3ZlKGMAbgoZuxgo06SB0Gkm5dQcmzZxOC8a2sgy7lfThMXI1Cik8pk-2NHiTFYVGFCltCZtnU1d-dGFFDafNqmbRuo4x3Ne92gfCjEf9p-NBHiSe7oO7QvBUtOrHDSDdC9B0_aLpS1L0UxB1tTdfcPlTmJoHUDiPOQqduaBa8Tm-ANRI2Q3TcuwhiAkIvM5Ycvs4k2XchLAazDn_k5m_1NTzriQc2ufi69Tk3OE9JMdrmA6JFw4EgoO0TJq4DrZ6rORqTg_A
